defaults:
  - iterative_sgd
  - perturber: batch
  - perturber/initializer: constant
  - perturber/gradient_modifier: sign
  - perturber/projector: mask_range
  - callbacks: [progress_bar, image_visualizer]
  - objective: zero_ap
  - gain: rcnn_training_loss
  - composer: overlay
  - enforcer/constraints@enforcer.rgb: [mask, pixel_range]

# Make a 5-step attack for the demonstration purpose.
optimizer:
  lr: 55

max_iters: 5

perturber:
  initializer:
    constant: 127
